image: node:lts

pipelines:
  branches:
    dev:
      - step:
          name: Deploy to Staging
          script:
            - npm install -g n
            - n $(node -p "require('./package.json').engines.node")
            - hash -r
            - node --version
            - npm install -g pnpm@latest
            - pnpm install
            - pnpm run build
            - node scripts/gen-wrangler.js staging
            - export CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
            - pnpm exec wrangler deploy
          # Define these variables in Repository Settings > Repository variables:
          # - CLOUDFLARE_API_TOKEN         (secured)
          # - STAGING_CORS_ALLOWED_ORIGINS
          # - STAGING_KV_ID

    main:
      - step:
          name: Deploy to Production
          script:
            - npm install -g n
            - n $(node -p "require('./package.json').engines.node")
            - hash -r
            - node --version
            - npm install -g pnpm@latest
            - pnpm install
            - pnpm run build
            - node scripts/gen-wrangler.js production
            - export CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
            - pnpm exec wrangler deploy
          # Define these variables in Repository Settings > Repository variables:
          # - CLOUDFLARE_API_TOKEN         (secured)
          # - PRODUCTION_CORS_ALLOWED_ORIGINS
          # - PRODUCTION_KV_ID
